language: node_js
node_js:
- "4"  # nodejs的版本
branches:
  only:
  - dev  # 设置自动化部署的分支
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli
# 解密id_rsa_blog.enc 输出到.ssh/文件夹下，命名为id_rsa_blog
- openssl aes-256-cbc -K $encrypted_4311f226e9a6_key -iv $encrypted_4311f226e9a6_iv -in .travis/id_rsa_blog.enc -out ~/.ssh/id_rsa_blog -d
# 设置id_rsa_blog文件权限
- chmod 600 ~/.ssh/id_rsa_blog
# 添加ssh密钥
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_blog
# 添加ssh配置文件
- cp .travis/ssh_config ~/.ssh/config
# 设置github账户信息
- git config --global user.name "iyongzai" #设置github用户名
- git config --global user.email iyongzai@qq.com #设置github用户邮箱
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean && hexo g -d